import { Nav, NavLink } from "@/components";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav>
          <NavLink href="/recipes">Recipes</NavLink>
          <NavLink href="/ingredients">Ingredients</NavLink>
          <NavLink href="/styles">Styles</NavLink>
        </Nav>
        {children}
      </body>
    </html>
  );
}
