import { Nav, NavLink } from "@/components";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Nunito_Sans } from "next/font/google";

const inter = Nunito_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Nav>
          <NavLink href="/recipes">Recipes</NavLink>
          <NavLink href="/ingredients">Ingredients</NavLink>
          <NavLink href="/profiles">Profiles</NavLink>
          <NavLink href="/styles">Styles</NavLink>
        </Nav>
        <main className="top-16 min-h-screen min-w-full left-2 right-2 flex flex-col items-center justify-between p-2">
          {children}
        </main>
      </body>
    </html>
  );
}
